version: '3.3'
services:
  #pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
        - "5050:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin

  #serveur de base de donnees
  db:
    image: 'postgres:13.1-alpine'
    container_name: db-container
    environment:
      - POSTGRES_DB=projet
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  back:
    image: 'back'
    container_name: back-container
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/projet
      - SPRING_DATASOURCE_USERNAME=db
      - SPRING_DATASOURCE_PASSWORD=db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db

  portainer:
    container_name: portainer-portainer
    image: portainer/portainer-ce
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db:
  portainer_data:
  pgadmin-data: